### ISSUE TITLE
Calculation of the volumes and drug concentrations in epithelial lining fluid, epithelium, and subepithelium

### ISSUE THREAD

**Issue by FeifanXie** [Open-Systems-Pharmacology/Inhalation-model#3]
Dear Moriah,

I came across your great work for the MoBi implementation of the inhalation model published by Boger, E et al., and I had some questions about this inhalation model in MoBi. 

I am a bit confused about the calculation of volumes and drug concentrations for the epithelial lining fluid (ELF), epithelium, and subepithelium in different generations. I took the 20th generation as an example. The calculations of the volume and drug concentration for ELF are shown as follows in your MoBi implementation.

Parameter: Inhaled ciprofloxacin|Organism|Lung|AlveolarRegion|Generation_20|EpithelialLiningFluid|Volume
IsFixed: False
Value: 7.47568204220349E-11 [l]
Formula: L*pi*h_ELF*(D-h_ELF)
L: Inhaled ciprofloxacin|Organism|Lung|AlveolarRegion|Generation_20|Airway length(0.0085 [dm])
h_ELF: Inhaled ciprofloxacin|Organism|Lung|AlveolarRegion|Generation_20|EpithelialLiningFluid|Height of epithelial lining fluid(7E-07 [dm])
D: Inhaled ciprofloxacin|Organism|Lung|AlveolarRegion|Generation_20|Airway diameter(0.004 [dm])
L: ..|..|Airway length
h_ELF: ..|Height of epithelial lining fluid
D: ..|..|Airway diameter

Parameter: Inhaled ciprofloxacin|Organism|Lung|AlveolarRegion|Generation_20|EpithelialLiningFluid|Ciprofloxacin|Concentration
IsFixed: False
Value: 0 [µmol/l]
Formula: V>0 ? M/V : 0
M: Inhaled ciprofloxacin|Organism|Lung|AlveolarRegion|Generation_20|EpithelialLiningFluid|Ciprofloxacin(0 [µmol])
V: Inhaled ciprofloxacin|Organism|Lung|AlveolarRegion|Generation_20|EpithelialLiningFluid|Volume(7.47568204220349E-11 [l])

The calculated volume for ELF is 7.47568204220349E-11 L, and I think this is the volume for only one airway in this generation. For the 20th generation, there are 524,288 airways in total, so the total volume for ELF in this generation should be 7.47568204220349E-11 L multiplied by 524,288, right? If this is ture, the drug concentration should be determined as the amount of drug in ELF in the 20th generation devided by total volume of ELF in the 20th generation. However, it seems that you used the volume of ELF in one airway for the calculation of drug concentration? And drug amout in ELF defined in the model looks like the total amount in all airways for this generation.

Following to my aforementioned confusion, the total volume for ELF, epithelium, and subepithelium in all generations is quite small (0.0588 L based on my caclutation, see belows for the details). This is much smaller than the acutal lung volume (0.57 L=0.0076* 70 kg* 1.0 g/cm3).  My question is if I want to calculate the drug concentrations separately in the total lungs, in the tracheobronchial region (generations 1-16), and in the alveolar region (generations 17-24), I do not know how to use the appropriate volume values.

Generation | ELF (L) | epithelium (L) | subepithelium | Airways | Total volume in each  generation
1 | 5.45E-05 | 2.99E-04 | 2.58E-03 | 1 | 2.93E-03
2 | 1.47E-05 | 7.37E-05 | 7.06E-04 | 2 | 1.59E-03
3 | 3.98E-06 | 2.01E-05 | 1.97E-04 | 4 | 8.83E-04
4 | 1.07E-06 | 5.44E-06 | 5.51E-05 | 8 | 4.93E-04
5 | 1.44E-06 | 7.33E-06 | 7.61E-05 | 16 | 1.36E-03
6 | 9.42E-07 | 4.81E-06 | 5.17E-05 | 32 | 1.84E-03
7 | 6.32E-07 | 3.25E-06 | 3.62E-05 | 64 | 2.57E-03
8 | 4.40E-07 | 2.27E-06 | 2.63E-05 | 128 | 3.72E-03
9 | 2.98E-07 | 1.55E-06 | 1.89E-05 | 256 | 5.31E-03
10 | 1.14E-07 | 2.91E-07 | 3.98E-07 | 512 | 4.11E-04
11 | 8.18E-08 | 2.08E-07 | 2.86E-07 | 1024 | 5.90E-04
12 | 5.80E-08 | 1.48E-07 | 2.05E-07 | 2048 | 8.42E-04
13 | 4.27E-08 | 1.10E-07 | 1.52E-07 | 4096 | 1.25E-03
14 | 3.02E-08 | 7.78E-08 | 1.09E-07 | 8192 | 1.78E-03
15 | 2.32E-08 | 5.99E-08 | 8.42E-08 | 16384 | 2.74E-03
16 | 1.79E-08 | 4.63E-08 | 6.55E-08 | 32768 | 4.25E-03
17 | 1.58E-10 | 8.16E-10 | 5.00E-09 | 65536 | 3.91E-04
18 | 1.22E-10 | 6.32E-10 | 3.87E-09 | 131072 | 6.06E-04
19 | 9.45E-11 | 4.88E-10 | 2.99E-09 | 262144 | 9.37E-04
20 | 7.48E-11 | 3.86E-10 | 2.37E-09 | 524288 | 1.48E-03
21 | 5.93E-11 | 3.06E-10 | 1.88E-09 | 1048576 | 2.35E-03
22 | 4.88E-11 | 2.52E-10 | 1.55E-09 | 2097152 | 3.87E-03
23 | 3.85E-11 | 1.99E-10 | 1.22E-09 | 4194304 | 6.11E-03
24 | 3.31E-11 | 1.71E-10 | 1.05E-09 | 8388608 | 1.05E-02

Thanks in advanced.

**Comment by moPellowe** [comment]
Hi Feifan. 

I think that you are right. With the volumes, you can also see that the mass transfer rate (see image below) is calculated for a single airway and then multiplied by N. And looking more closely, it looks like there is an error in the formula according to your comment above. 
I will adjust the volumes and the transfer rates to look at the total number of airways.
![image](https://user-images.githubusercontent.com/57540473/216768630-09185c1a-c0a0-483d-8721-7165fd8a5189.png)

**Comment by moPellowe** [comment]
Changes have been made (see #4 )

Regarding the total lung volume, the current implementation reflects the assumptions of Boger and Wigstrom (2018), so perhaps you can check there for the justification for the lung volume used?

**Comment by FeifanXie** [comment]
Hi Moriah,

Thanks for your feedback.

I had a look at your updated MoBi file, and I have a further question about the formula of mass transfer rate. Taking the mass transfer rate of ELF to epithelium formula as an example: pi*D*L*P*(f_u_ELF*A_ELF/V_ELF - A_epi/V_epi/K_p_u_lung). Per my understanding, now the V_ELF represents the ELF volume of all the airways (N*L*pi*h_ELF*(D-h_ELF)) in a specific generation. In this equation, the term “pi*D*L*P” only represents the drug clearance from ELF to epithelium in a single airway, and overall drug clearance in all airways of a generation should be “N*pi*D*L*P”. If so, should the formula be written as: N*pi*D*L*P*(f_u_ELF*A_ELF/V_ELF - A_epi/V_epi/K_p_u_lung)?

As for the total lung volume, I understand the calculation in the Boger and Wigstrom (2018) paper. That is, actual lung volume is determined as: lung fraction (0.076) of body weight* body weight (70 kg) * lung density (1.0 g/cm3) , and the calculated lung volume is 0.532 L. However, if I added up the volumes of ELF, epithelium, and subepithelium in all generations in your MoBi implementation, the calculated lung volume is only 0.0588 L, which is much smaller than actual lung volume. I now realize that the inconsistency is probably due to the neglection of the extent of alveolarization. In another Boger paper (2019, https://doi.org/10.1089/jamp.2017.1436), the alveolarization correction for the volumes of ELF, epithelium, and subepithelium was described in details in the article supplement, and by doing so the inconsistency is eliminated.

It seems that you implemented the alveolarization impact on the cross-sectional areas, but unfortunately the relevant volumes in the alveolar generation was not corrected. To help you better know what I mean, I attached an excel file showing my calculation of lung volume based on your MoBi implementation and corrected calculation after accounting for the alveolarization. In my opinion, it would be more correct to use the alveolarization adapted volumes.

I am looking forward to your comments. Thank you for your time.

Kind regards,

Feifan

发件人: Moriah Pellowe ***@***.***>
发送时间: 2023年2月4日 22:19
收件人: Open-Systems-Pharmacology/Inhalation-model ***@***.***>
抄送: FeifanXie ***@***.***>; Author ***@***.***>
主题: Re: [Open-Systems-Pharmacology/Inhalation-model] Calculation of the volumes and drug concentrations in epithelial lining fluid, epithelium, and subepithelium (Issue #3)


Changes have been made (see #4<https://github.com/Open-Systems-Pharmacology/Inhalation-model/pull/4> )

Regarding the total lung volume, the current implementation reflects the assumptions of Boger and Wigstrom (2018), so perhaps you can check there for the justification for the lung volume used?

**Comment by moPellowe** [comment]
The volumes and surface areas have been adjusted according to the supplemental document (Boger & Friden, 2019) (see #5 ). Thank you for pointing this out. Please let me know if you find any other discrepancies to be corrected.
